# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/perform_stats',
                'doc_host': 'https://silvaac.github.io',
                'git_url': 'https://github.com/silvaac/perform_stats',
                'lib_path': 'perform_stats'},
  'syms': {'perform_stats.core': {'perform_stats.core.foo': ('core.html#foo', 'perform_stats/core.py')}}}
